export {default as NewProduct} from './newProduct/NewProduct';
export {default as Product} from './product/Product';
export {default as ProductList} from './productList/ProductList';
export {default as Home} from "./home/Home";
export {default as Login} from  "./login/Login";
export {default as List}  from "./list/List";
export {default as Single}  from "./single/Single";
export {default as New} from "./new/New";
export {default as Dashboard} from './Dashboard/Dashboard';
export {default as Landing } from './Landing/Landing';
export {default as Onboard} from './Onboard/Onboard';
export {default as Onboard2} from './Onboard/Onboard2';